title = "rbx-faker"
gitSourceBranch = "main"

[home]
enabled = true

[[home.features]]
title = "Yield-free"
description = "None of rbx-faker's methods yield, allowing for quick story testing."

[docusaurus]
tagline = "A library that generates Roblox data such as group icons and display names, inspired by faker-js."