[package]
name = "synpixel/faker"
description = "A library that fetches random Roblox user data, inspired by faker-js."
version = "0.2.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["synpixel"]

exclude = ["**"]
include = ["src", "src/*", "users/out.json", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]